= Trabajo Práctico de Bases de Datos
Luna Nicolás <nluna190898@gmail.com>; @Montenegro Tomás <tomymontenegro1999@gmail.com>; Sandoval Maximiliano <maxisandoval98@gmail.com>;
v1, {docdate}. Docentes Hernán Rondelli y Hernán Czemerinski
:title-page:
:numbered:
:source-highlighter: coderay
:tabsize: 4



== Introducción

En el presente documento, se presentará el software de gestión de tarjetas y las funcionalidades que rodean a esta. Por medio de un modelo de bases de datos, representaremos, todos los tipos de entidades que vamos a usar, como lo es el caso de los clientes, las tarjetas, los comercios, los consumos, etc, que se verán a lo largo del desarrollo de este informe.

Las instancias centrales para su respectivo desarrollo, serán el modelo de datos, la creación propiamente dicha de la base de datos (una principal SQL y otra secundaría NoSQL para su comparativa), la carga de los datos y las distintas funcionalidades que tendrá el sistema, por medio de Stored Procedures y Triggers. Cabe destacar, que para poder representar e interactuar con el software, utilizaremos una interfaz CLI (un super menú, por medio de la terminal). 

Emplearemos las tecnologías de PostgreSQL y Go para la construcción de la aplicación.

== Descripción
En esta sección vamos a detallar cronológicamente, como fuimos estructurando y organizando el proyecto.
En primer lugar, se desarrollo los sedimentos del trabajo, estos son la base de dato relacional, las tablas (con sus atributos y tipos de datos especificados), agregamos las pks y las fks cuando correspondían. No obstante, contemplamos si es que ya existía con anterioridad, la base de datos, en el equipo que ejecute nuestro software, tomamos la decisión de sobrescribirla. 

Es importante mencionar, que, para la correcta ejecución de nuestro aplicativo, decimos instanciar una serie de datos en cada tabla, con diferentes escenarios (tanto exitosos, como operaciones invalidas), para poder testear a fondo el sistema.

Luego, por su parte, dotamos la base de datos de funcionalidad, por medio de Stored Procedures y Triggers. Los métodos que incorporamos fueron, autorización de compra, generación del resumen y alertas a clientes.

Y finalmente, a modo de comparativa, guardaremos datos de clientes, tarjetas, comercios, y compras en una base de datos NoSQL (en BoltDB), con la estructura JSON respectiva. Más adelante se analizará su comportamiento, las diferencias y similitudes que tiene con una base de datos relacional.

== Implementación

== Conclusiones